config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'user_searches#home', as: 'home'
  get 'help', to: 'user_searches#help'
  get 'my_searches', to: 'user_searches#my_searches'
  get 'search', to: 'cars#search'
  devise_for :users
  resources :cars
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  TEXT_REGEX = /\A[a-zA-Z]+\z/
  paginates_per 3
  validates :date_added, presence: true
  validates :price, :odometer, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :year, numericality: { only_integer: true, greater_than: 1900, less_than_or_equal_to: Time.zone.now.year }
  validates :make, :model, length: { minimum: 3, maximum: 50 },
                           format: { with: TEXT_REGEX, message: I18n.t('make_model_error') }
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  has_many :searches_users, dependent: :delete_all
  has_many :users, through: :searches_users

  validates :year_from, :year_to, :price_from, :price_to, numericality: { only_integer: true, allow_nil: true }

  scope :with_params, lambda { |params|
                        where(make: params[:make].downcase,
                              model: params[:model].downcase,
                              year_from: params[:year_from].presence,
                              year_to: params[:year_to].presence,
                              price_from: params[:price_from].presence,
                              price_to: params[:price_to].presence)
                      }

  def self.normalize_params(params)
    normalized_params = params.dup
    normalized_params[:make] = normalized_params[:make].downcase if normalized_params[:make].present?
    normalized_params[:model] = normalized_params[:model].downcase if normalized_params[:model].present?
    normalized_params
  end
end

app/models/searches_user.rb
# frozen_string_literal: true

class SearchesUser < ApplicationRecord
  belongs_to :search
  belongs_to :user

  scope :with_params, lambda { |params|
                        where(search_id: params[:search_id],
                              user_id: params[:user_id])
                      }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :searches_users, dependent: :delete_all
  has_many :searches, through: :searches_users

  validate :password_complexity, :email_complexity

  PASSWORD_REGEX = /^(?=.*[A-Z])(?=(?:.*[~@$!#%*^(){}_?&]){2})[a-zA-Z0-9~@$!#%*^(){}_?&]{8,20}$/
  EMAIL_REGEX = /^([a-zA-Z0-9+_.-]{5,})@([a-zA-Z0-9+_.-]+\.)+[a-zA-Z]{2,4}$/

  def password_complexity
    if password.blank? ||
       password =~ PASSWORD_REGEX
      return
    end

    errors.add :password, I18n.t('password_error')
  end

  def email_complexity
    return if email.blank? || email =~ EMAIL_REGEX

    errors.add :email, I18n.t('email_error')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_locale, :authenticate_user!

  def set_locale
    I18n.locale = locale_param || cookies_locale || I18n.default_locale
    locale_cookie_set(I18n.locale) if locale_param.present?
  end

  private

  def locale_param
    params[:lang]&.to_sym
  end

  def cookies_locale
    cookies[:lang]&.to_sym
  end

  def locale_cookie_set(locale)
    cookies[:lang] = { value: locale, expire: 1.year.from_now }
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index search]

  # GET /cars
  def index
    save_params_to_session if given_params?
    SearchSaverService.call(search_params, current_user) if given_params? && current_user
    @cars = SearchService.call(search_params)
    sort_cars if params[:sort_by].present?
    @cars = @cars.page(params[:page])
  end

  def search; end

  # GET /cars/1
  def show; end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit; end

  # POST /cars
  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to car_url(@car), notice: t('.notice')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      redirect_to car_url(@car), notice: t('.notice')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy

    redirect_to cars_url, notice: t('.notice')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:make, :model, :year, :odometer, :price, :description, :date_added)
  end

  def search_params
    params.permit(:make, :model, :year_from, :year_to, :price_from, :price_to)
  end

  def given_params?
    [params[:make], params[:model], params[:year_from], params[:year_to], params[:price_from], params[:price_to]]
      .any?(&:present?)
  end

  def save_params_to_session
    session[:previous_params] = params
  end

  def sort_cars
    if session[:previous_params].present?
      session[:previous_params] = session[:previous_params].transform_keys(&:to_sym)
      @cars = SearchService.call(session[:previous_params])
    end
    @cars = CarSortingService.call(@cars, params[:sort_by])
  end
end

app/controllers/user_searches_controller.rb
# frozen_string_literal: true

class UserSearchesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home help]

  def home
    session[:previous_params] = nil
  end

  def help; end

  def my_searches
    @user = User.find(current_user.id)
    @my_searches = @user.searches.all
  end
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <tr>
    <th scope="row"><%= car.id %></th>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= car.odometer %></td>
      <td><%= car.price %></td>
      <td><%= car.description %></td>
      <td><%= car.date_added %></td>
  </tr>
</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= t('error') %> : <%= car.errors.count %> - <%= t('error_message') %></h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t('make'), style: "display: block" %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label t('model'), style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label t('year'), style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label t('odometer'), style: "display: block" %>
    <%= form.number_field :odometer %>
  </div>

  <div>
    <%= form.label t('price'), style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label t('description'), style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label t('date_added'), style: "display: block" %>
    <%= form.date_field :date_added %>
  </div>

  <div>
    <%= form.submit t('create_car')%>
  </div>
<% end %>

app/views/cars/_search_rules.html.erb
<% if session[:previous_params].present? %>
<div id="search_rules"> 
     <div><%= t('make') %> : <%=session[:previous_params][:make] %></div>
     <div><%= t('model') %> : <%= label_tag :model, session[:previous_params][:model] %></div>
     <div><%= t('years') %> : <%= label_tag :year_from, session[:previous_params][:year_from] %> - <%= label_tag :year_to, session[:previous_params][:year_to] %></div>
     <div><%= t('price') %> : <%= label_tag :price_from, session[:previous_params][:price_from] %> - <%= label_tag :price_to, session[:previous_params][:price_to] %></div>
</div>
<% end %>

app/views/cars/edit.html.erb
<h1><%= t('edit_car') %></h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to t('show_car'), @car %> |
  <%= link_to t('cars_list'), cars_path %>
</div>

<%= render 'share/footer' %>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('.hello') %></h1>

<h3><%= t('.total_quantity') %> <%= @cars.total_count %></h3> 

<%= render 'search_rules' if session[:previous_params].present? %>

<div>
  <%= form_with url: cars_path, method: :get, data: { turbo: false }, class: 'form-inline' do |f| %>
    <%= f.label :sort_by, t('.sort_order') %>
    <%= f.select :sort_by, [[t('.date_added_desc'), 'date_added_desc'], [t('.date_added_asc'), 'date_added_asc'], [t('.price_desc'), 'price_desc'], [t('.price_asc'), 'price_asc']], selected: params[:sort_by] %>
    <%= f.submit t('.sort') %>
  <% end %>
</div>

<div id="cars">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col"><%= t('make') %></th>
      <th scope="col"><%= t('model') %></th>
      <th scope="col"><%= t('year') %></th>
      <th scope="col"><%= t('odometer') %></th>
      <th scope="col"><%= t('price') %></th>
      <th scope="col"><%= t('description') %></th>
      <th scope="col"><%= t('date added') %></th>
    </tr>
  </thead>
  <tbody>
  <% @cars.each do |car| %>
    <%= render car %>
  <% end %>
  </tbody>
  </table>

  <%= paginate @cars %>
</div>

<%= render 'share/footer' %>

app/views/cars/new.html.erb
<h1><%= t('new_car') %></h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to t('cars_list'), cars_path %>
</div>

<%= render 'share/footer' %>

app/views/cars/search.html.erb
<h1><%= t('.rules') %></h1>

<div>
  <%= form_with url: cars_path, method: :get, data: { turbo: false } do |f| %>
  <div class="form-group">
    <%= f.label :make, t('make') %>
    <%= f.text_field :make, value: params[:make]%>
  </div> 
   <div class="form-group"> 
    <%= f.label :model, t('model') %>
    <%= f.text_field :model, value: params[:model]%>   
  </div>
  <div class="form-group">
    <%= f.label :year, t('years') %> 
    <div>
       <%= f.number_field :year_from, value: params[:year_from] %>
       <%= f.number_field :year_to, value: params[:year_to] %> 
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, t('price') %>
    <div>
       <%= f.number_field :price_from, value: params[:price_from] %>
       <%= f.number_field :price_to, value: params[:price_to] %> 
    </div>
  </div>
    <%= f.submit t('.search'), class: 'btn btn-primary' %>
  <% end %>
</div>

<%= render 'share/footer' %>

app/views/cars/show.html.erb
<%= render @car %>

<div>
  <%= link_to t('edit_car'), edit_car_path(@car) %> |
  <%= link_to t('cars_list'), cars_path %>

  <%= button_to t('destroy_car'), @car, method: :delete %>
</div>

<%= render 'share/footer' %>

app/views/share/_footer.html.erb
<%= button_to t('back_home'), home_path, method: :get, class: 'btn btn-primary' %> 

app/views/share/_header.html.erb
<div>
    <%= link_to "English", request.query_parameters.merge(lang: :en) %> 
    <%= link_to "Ukrainian", request.query_parameters.merge(lang: :uk) %>  
</div>

<% if user_signed_in? %>
    <%= button_to t('my_searches'), my_searches_path,  method: :get, class: 'btn btn-primary' %>
    <%= button_to t('add car'), new_car_path,  method: :get, class: 'btn btn-primary' %>
    <div> <%= t('hello') %> <%= current_user.email %> </div>
    <%= button_to t('log_out'), destroy_user_session_path, method: :delete, data: { turbo: false}, class: 'btn btn-primary' %>
<% else %>
    <%= button_to t('log_in'), new_user_session_path, method: :get, class: 'btn btn-primary' %>
    <%= button_to t('sign_up'), new_user_registration_path, method: :get, class: 'btn btn-primary' %>
 <% end %>

app/views/user_searches/_my_search.html.erb
<div>
  <tr>
    <th scope="row"><%= my_search.id %></th>
      <td><%= my_search.make %></td>
      <td><%= my_search.model %></td>
      <td><%= my_search.year_from %></td>
      <td><%= my_search.year_to %></td>
      <td><%= my_search.price_from %></td>
      <td><%= my_search.price_to %></td>
  </tr>
</div>

app/views/user_searches/help.html.erb
<h1> <%= t('.help') %> </h1>
<pre> <%= t('.help_info', option1: t('search'), option2: t('cars_list'), option3: t('help')) %> </pre> 
<%= render 'share/footer' %>

app/views/user_searches/home.html.erb
<h1> <%= t('hello') %> </h1>

<%= button_to t('help'), help_path, method: :get %>
<%= button_to t('cars_list'), cars_path, method: :get %>
<%= button_to t('search'), search_path, method: :get %>

app/views/user_searches/my_searches.html.erb
<h1><%= t('.my_searches') %></h1>

<div id="searches">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col"><%= t('make') %></th>
      <th scope="col"><%= t('model') %></th>
      <th scope="col"><%= t('.year_from') %></th>
      <th scope="col"><%= t('.year_to') %></th>
      <th scope="col"><%= t('.price_from') %></th>
      <th scope="col"><%= t('.price_to') %></th>
    </tr>
  </thead>
  <tbody>
  <% @my_searches.each do |my_search| %>
    <%= render 'user_searches/my_search', { my_search: my_search } %>
  <% end %>
  </tbody>
  </table>
  </div>

  <%= render 'share/footer' %>